module.exports = (sequelize,  DataTypes)=> {
    const dataInduk = sequelize.define(
        'data_induk',
        {
            id:{
                type:DataTypes.INTEGER,
                primaryKey: true,
                autoIncrement: true,
            },
            nama:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            jk:{
                type:DataTypes.STRING,
                allowNull:false,
            },
            nisn:{
                type:DataTypes.STRING,
                allowNull:false,
            },
            tempat_lahir:{
                type:DataTypes.STRING,
                allowNull:false,
            },
            tanggal_lahir:{
                type:DataTypes.DATE,
                allowNull:false,
            },
            nik:{
                type:DataTypes.INTEGER,
                allowNull:false,
            },
            agama:{
                type:DataTypes.STRING,
                allowNull:false,
            },
            alamat:{
                type:DataTypes.STRING,
                allowNull:false,
            },
            rt:{
                type:DataTypes.INTEGER,
                allowNull:true,
            },
            rw:{
                type:DataTypes.INTEGER,
                allowNull:true,
            },
            dusun:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            kelurahan:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            kecamatan:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            kode_pos:{
                type:DataTypes.INTEGER,
                allowNull:true,
            },
            jenis_tinggal:{
                type:DataTypes.STRING,
                allowNull:true
            },
            alat_transportasi:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            telepon:{
                type:DataTypes.STRING,
                allowNull:true
            },
            hp:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            email:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            skhun:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            penerima_kps:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            no_kps:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            nama_ayah:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            tahun_lahir_ayah:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            jenjang_pendidikan_ayah:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            pekerjaan_ayah:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            penghasilan_ayah:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            nik_ayah:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            nama_ibu:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            tahun_lahir_ibu:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            jenjang_pendidikan_ibu:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            pekerjaan_ibu:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            penghasilan_ibu:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            nik_ibu:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            nama_wali:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            tahun_lahir_wali:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            jenjang_pendidikan_wali:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            pekerjaan_wali:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            penghasilan_wali:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            nik_wali:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            rombel_saat_ini:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            no_peserta_ujian_nasional:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            no_seri_ijazah:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            penerima_kip:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            nomor_kip:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            nama_di_kip:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            nomor_di_kks:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            no_registrasi_akta_lahir:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            bank:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            nomor_rekening_bank:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            rekening_atas_nama:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            layak_pip_usulan_sekolah:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            alasan_layak:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            kebutuhan_khusus:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            sekolah_asal:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            anak_ke:{
                type:DataTypes.INTEGER,
                allowNull:true,
            },
            lintang:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            bujur:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            no_kk:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            berat_badan:{
                type:DataTypes.INTEGER,
                allowNull:true,
            },
            tinggi_badan:{
                type:DataTypes.INTEGER,
                allowNull:true,
            },
            lingkar_kepala:{
                type:DataTypes.INTEGER,
                allowNull:true,
            },
            jml_saudara_kandung:{
                type:DataTypes.INTEGER,
                allowNull:true,
            },
            jarak_rumah_ke_sekolah:{
                type:DataTypes.INTEGER,
                allowNull:true,
            },
            tahun_ajaran:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            bulan_masuk:{
                type:DataTypes.STRING,
                allowNull:true,
            },
            tahun_masuk:{
                type:DataTypes.STRING,
                allowNull:true,
            },
        },{
            tableName:'data_induk'
        }
    );
    return dataInduk;
}